# Generated by Django 3.1 on 2020-08-10 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion_Huevo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clasificacion de Huevos',
                'verbose_name_plural': 'Clasificaciones de Huevos',
            },
        ),
        migrations.CreateModel(
            name='Corral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corral',
                'verbose_name_plural': 'Corrales',
            },
        ),
        migrations.CreateModel(
            name='Huevos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrodb.clasificacion_huevo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Huevo',
                'verbose_name_plural': 'Huevos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Lote_Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=25, null=True)),
                ('genetica', models.CharField(max_length=100, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_produccion', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_produccion', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('corral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agrodb.corral')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agrodb.proveedor')),
            ],
            options={
                'verbose_name': 'Lote de Animales',
                'verbose_name_plural': 'Lotes de Animales',
            },
        ),
        migrations.CreateModel(
            name='Jornada_Recoleccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_jornada', models.DateField()),
                ('momento_jornada', models.CharField(choices=[('MN', 'Mañana'), ('MD', 'Mediodía'), ('TD', 'Tarde')], default='MN', max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('huevos', models.ManyToManyField(related_name='huevos', to='agrodb.Huevos')),
                ('lote_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrodb.lote_animal')),
            ],
            options={
                'verbose_name': 'Jornada de Recolección',
                'verbose_name_plural': 'Jornadas de Recolección',
            },
        ),
        migrations.CreateModel(
            name='Granja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Granja',
                'verbose_name_plural': 'Granjas',
            },
        ),
        migrations.AddField(
            model_name='corral',
            name='granja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agrodb.granja'),
        ),
    ]
